// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystemDAL.EntityFramework;

namespace TicketingSystemDAL.Migrations
{
    [DbContext(typeof(TicketingSystemDbContext))]
    [Migration("20250422061102_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicketingSystemDAL.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SetupTime")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TeardownTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.EventSeat", b =>
                {
                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("SeatId", "EventId");

                    b.HasIndex("EventId");

                    b.HasIndex("StatusId");

                    b.ToTable("EventSeats");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.EventSeatStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EventSeatStatuses");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.EventStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("EventStatuses");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.EventVenue", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("EventId", "VenueId");

                    b.HasIndex("VenueId");

                    b.ToTable("EventVenues");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.SeatStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SeatStatuses");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.SeatsType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SeatsTypes");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfSeats")
                        .HasColumnType("int");

                    b.Property<int>("VenueTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueTypeId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionId");

                    b.ToTable("VenueRows");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueSeat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("RowId")
                        .HasColumnType("int");

                    b.Property<int?>("SeatStatusId")
                        .HasColumnType("int");

                    b.Property<int>("SeatsTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RowId");

                    b.HasIndex("SeatStatusId");

                    b.HasIndex("SeatsTypeId");

                    b.ToTable("VenueSeats");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("VenueSections");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("SeatsTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatsTypeId");

                    b.ToTable("VenueTypes");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.Event", b =>
                {
                    b.HasOne("TicketingSystemDAL.Entities.EventStatus", "Status")
                        .WithMany("Events")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.EventSeat", b =>
                {
                    b.HasOne("TicketingSystemDAL.Entities.Event", "Event")
                        .WithMany("EventSeats")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystemDAL.Entities.VenueSeat", "Seat")
                        .WithMany("EventSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystemDAL.Entities.EventSeatStatus", "Status")
                        .WithMany("EventSeats")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Seat");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.EventVenue", b =>
                {
                    b.HasOne("TicketingSystemDAL.Entities.Event", "Event")
                        .WithMany("EventVenues")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TicketingSystemDAL.Entities.Venue", "Venue")
                        .WithMany("EventVenues")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.Venue", b =>
                {
                    b.HasOne("TicketingSystemDAL.Entities.VenueType", "VenueType")
                        .WithMany("Venues")
                        .HasForeignKey("VenueTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenueType");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueRow", b =>
                {
                    b.HasOne("TicketingSystemDAL.Entities.VenueSection", "Section")
                        .WithMany("VenueRows")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueSeat", b =>
                {
                    b.HasOne("TicketingSystemDAL.Entities.VenueRow", "Row")
                        .WithMany("VenueSeats")
                        .HasForeignKey("RowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketingSystemDAL.Entities.SeatStatus", null)
                        .WithMany("VenueSeats")
                        .HasForeignKey("SeatStatusId");

                    b.HasOne("TicketingSystemDAL.Entities.SeatsType", "SeatsType")
                        .WithMany("VenueSeats")
                        .HasForeignKey("SeatsTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Row");

                    b.Navigation("SeatsType");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueSection", b =>
                {
                    b.HasOne("TicketingSystemDAL.Entities.Venue", "Venue")
                        .WithMany("VenueSections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueType", b =>
                {
                    b.HasOne("TicketingSystemDAL.Entities.SeatsType", null)
                        .WithMany("VenueTypes")
                        .HasForeignKey("SeatsTypeId");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.Event", b =>
                {
                    b.Navigation("EventSeats");

                    b.Navigation("EventVenues");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.EventSeatStatus", b =>
                {
                    b.Navigation("EventSeats");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.EventStatus", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.SeatStatus", b =>
                {
                    b.Navigation("VenueSeats");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.SeatsType", b =>
                {
                    b.Navigation("VenueSeats");

                    b.Navigation("VenueTypes");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.Venue", b =>
                {
                    b.Navigation("EventVenues");

                    b.Navigation("VenueSections");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueRow", b =>
                {
                    b.Navigation("VenueSeats");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueSeat", b =>
                {
                    b.Navigation("EventSeats");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueSection", b =>
                {
                    b.Navigation("VenueRows");
                });

            modelBuilder.Entity("TicketingSystemDAL.Entities.VenueType", b =>
                {
                    b.Navigation("Venues");
                });
#pragma warning restore 612, 618
        }
    }
}
